(cl:defpackage dome-srv
  (:use )
  (:export
   "CLOSE_DOME"
   "<CLOSE_DOME-REQUEST>"
   "CLOSE_DOME-REQUEST"
   "<CLOSE_DOME-RESPONSE>"
   "CLOSE_DOME-RESPONSE"
   "OPEN_DOME"
   "<OPEN_DOME-REQUEST>"
   "OPEN_DOME-REQUEST"
   "<OPEN_DOME-RESPONSE>"
   "OPEN_DOME-RESPONSE"
  ))

