/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/rosmgr/quimal/src/dome/msg/roof.msg
 *
 */


#ifndef DOME_MESSAGE_ROOF_H
#define DOME_MESSAGE_ROOF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dome
{
template <class ContainerAllocator>
struct roof_
{
  typedef roof_<ContainerAllocator> Type;

  roof_()
    : ubication(0.0)
    , sensor1(false)
    , sensor2(false)
    , sensor3(false)
    , state()  {
    }
  roof_(const ContainerAllocator& _alloc)
    : ubication(0.0)
    , sensor1(false)
    , sensor2(false)
    , sensor3(false)
    , state(_alloc)  {
    }



   typedef float _ubication_type;
  _ubication_type ubication;

   typedef uint8_t _sensor1_type;
  _sensor1_type sensor1;

   typedef uint8_t _sensor2_type;
  _sensor2_type sensor2;

   typedef uint8_t _sensor3_type;
  _sensor3_type sensor3;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::dome::roof_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dome::roof_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct roof_

typedef ::dome::roof_<std::allocator<void> > roof;

typedef boost::shared_ptr< ::dome::roof > roofPtr;
typedef boost::shared_ptr< ::dome::roof const> roofConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dome::roof_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dome::roof_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dome

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/rosmgr/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'dome': ['/home/rosmgr/quimal/src/dome/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dome::roof_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dome::roof_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dome::roof_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dome::roof_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dome::roof_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dome::roof_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dome::roof_<ContainerAllocator> >
{
  static const char* value()
  {
    return "904d6c5ea52702f7baaa63d7589e3626";
  }

  static const char* value(const ::dome::roof_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x904d6c5ea52702f7ULL;
  static const uint64_t static_value2 = 0xbaaa63d7589e3626ULL;
};

template<class ContainerAllocator>
struct DataType< ::dome::roof_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dome/roof";
  }

  static const char* value(const ::dome::roof_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dome::roof_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ubication\n\
bool sensor1\n\
bool sensor2\n\
bool sensor3\n\
string state\n\
";
  }

  static const char* value(const ::dome::roof_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dome::roof_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ubication);
      stream.next(m.sensor1);
      stream.next(m.sensor2);
      stream.next(m.sensor3);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct roof_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dome::roof_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dome::roof_<ContainerAllocator>& v)
  {
    s << indent << "ubication: ";
    Printer<float>::stream(s, indent + "  ", v.ubication);
    s << indent << "sensor1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor1);
    s << indent << "sensor2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor2);
    s << indent << "sensor3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor3);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOME_MESSAGE_ROOF_H
